using Models.Enums;
using System;

namespace WebApi.DTOs
{
    /// <summary>
    /// Transaction DTO
    /// </summary>
    public class TransactionDTO
    {
        public Guid Id { get; set; }
        public TransactionType Type { get; set; }
        /// <summary>
        /// Transaction numeric value. Incrementing or decrementing the account balance, based on the transaction type.
        /// </summary>        
        public decimal Amount { get; set; }
        /// <summary>
        /// Effective date-time, generated by the service, when the transaction is being stored.
        /// </summary>
        public DateTime EffectiveDate { get; set; }        
    }
}
